### ISSUE TITLE
Performance IO Issue

### ISSUE THREAD

**Issue by LucidAPs** [sehrschlechtYT/WanderingCollector#1]
Saving data and IO operations shouldn't be done on the main thread, especially the way this plugin works. Because the more you leave it on a server with lots of people the more intense the data lookups will become as the items volume increases.

https://spark.lucko.me/2vZmRFIBCM
https://www.spigotmc.org/attachments/upload_2021-11-26_16-56-5-png.665694/

**Comment by sehrschlechtYT** [comment]
Thanks for your Bug report, I'll try to fix that in the next days.

**Comment by sehrschlechtYT** [comment]
Hey @LucidAPs,

I've uploaded [a beta release](https://github.com/sehrschlechtYT/WanderingCollector/releases/tag/1.2.1) which should fix the problem by saving the config only every 20 seconds.

As I'm not able to test the plugin on a server with many players, it would be good if you could test it on your server.

**Comment by LucidAPs** [comment]
> Hey @LucidAPs,
> 
> I've uploaded [a beta release](https://github.com/sehrschlechtYT/WanderingCollector/releases/tag/1.2.1) which should fix the problem by saving the config only every 20 seconds.
> 
> As I'm not able to test the plugin on a server with many players, it would be good if you could test it on your server.

I am on it, please give me one or two days, and I will report back. Thank you for your work, much appreciate it.

**Comment by LucidAPs** [comment]
Not perfect, but a lot better. Its at 1% of the servers tick. I am happy :)

**Comment by sehrschlechtYT** [comment]
If the file gets too big, you can enable `items.clear-meta` in the config, which will only save the type of each item and remove data like durability, enchantments, custom name etc. I could also add support for MongoDB or MySQL, but I don't think that will use less storage.
